language: d

# latest dmd, gdc and ldc
d:
  - dmd
  - ldc

env:
  global:
    - secure: "oWH0za1XXEfALu5kTKpMbDBO++Vwg9518q2whp/QKWnscIcLo8tAA/EMi/H606HaeEs2IAqZJsVw3gH47nCuW/cffsYT1fn4xSqYCOOZS0ilvrpjWK/3M7QDzhcGOKpqespEoQ9hlF/lnWPzTQTdkBW4Sqwvqt/ZrCqlLVygu6HJIw344AXnn1sSlmG3O58+ZLOmszgauGZBVYJd1fzlep6phhU/QxWRfIHfBaOsxIe5g+M1JCT3T9sNT+2fXI/6OIixOUsTKWUIKMc1Mvv7MFLRqiMx+FyIfiU0wkysgFM5UE0uAM3jmJ4tyTGGW0Xv3wkI/OIbx7iZDjn2nTH4kFwrh1xzVbSTdiLx1lrGa9FMfBwxfEa/TsD1/OQXajKn2PJDzDxEpGrzF2Aolo9EzjMkIEnMXAJ72ywCXGY8P/p+Gph9YixHKifSOBR+YGf983yX4LWBXFPVGaeBaQ8R8oGfpRfCY4MflnkSkgWa9aHgW8qNAEVDXjhjAivAn961sdxrE5ra5dQjhAdv9K73rQG+V4sVu/TxMwVuQWgUA4j1Hj+sxorrS38WAflBASnyXumyHkDqqnK6Uxts+Cu0WPg8GI+mv4aOWXwqk2XP3aSIQALzd7oheYgkk/6AzpSr8R96cgQmIBhuMlRFetxv+1aORyOpGdu14eByY521ehs="

after_success:
  - ./push-ddoc.sh
